export enum WhatsAppType {
  INDICATION_ALERT = 'INDICATION_ALERT',

  LIST_ALERT = 'LIST_ALERT',

  LIST_ALERT_CHOOSED = 'LIST_ALERT_CHOOSED',

  LIST_MATCH_APPROVED = 'LIST_MATCH_APPROVED',

  LIST_MATCH_REPROVED = 'LIST_MATCH_REPROVED',

  CANCELED_TRAVEL = 'CANCELED_TRAVEL',
}
